#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpush
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Rpush init script
# Description:       Rpush init script
### END INIT INFO

# must be root
if [[ "$(whoami)" != "root" ]]; then
  echo "Must be run as root"
  exit 1
fi

# Get arguments
APP_NAME="$1"
COMMAND="$2"
ENVIRONMENT="$3"

# Config params
DESC="Service for Lixibox Rpush"
NAME=rpush
APP_ROOT=/data/lixibox/current
PID_DIR="/var/run/engineyard/rpush/${APP_NAME}"
PID_FILE="${PID_DIR}/rpush.pid"
CONFIG_FILE="${APP_ROOT}/config/initializers/rpush.rb"
APP_USER=$(stat -L -c"%U" "${APP_ROOT}")
RPUSH="${APP_ROOT}/ey_bundler_binstubs/rpush"

export HOME="/home/${APP_USER}"
cd "${APP_ROOT}"

start()
{
  sudo -u "${APP_USER}" -H "${RPUSH}" start -c "${CONFIG_FILE}" -e "${ENVIRONMENT}" -p "${PID_FILE}" &
  exit $?
}

stop()
{
  sudo -u "${APP_USER}" -H "${RPUSH}" stop -c "${CONFIG_FILE}" -e "${ENVIRONMENT}" -p "${PID_FILE}" &
  exit $?
}

# Execute
case $COMMAND in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
