default[:mongo_version] = "3.0.7" # "2.4.6"
default[:mongo_path] = "/usr"
default[:mongo_base] = "/data/mongodb"
default[:mongo_port] = "27017"
default[:total_memory_mb] = `df -m /data | awk '/dev/ {print $2}'`.to_i
default[:oplog_memory_percentage] = "0.1"
default[:oplog_size] = (default[:total_memory_mb] * default[:oplog_memory_percentage].to_f).to_i
default[:mongo_utility_instances] = node[:utility_instances].select { |ui| ui[:name][/mongodb/] }
default[:mongo_replset] = "mongodb"